# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "CI-kedja" ]
  pull_request:
    branches: [ "CI-kedja" ]

env:
  # JWT_SECRET: "DUMMYSECRETFORTESTINGJWT12345678"
  ATLAS_USERNAME: "oleg22"
  ATLAS_PASSWORD: DEyTL0mOhfjdcK8g"
  LOCAL_DSN: "mongodb://localhost:27017"
  DB_CLUSTER: "texteditor"
  DB_NAME: "docs"
  COLLECTION_NAME: "document"
  TEST_PORT: 4000
  PORT: 3000

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 20 

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    # - run: npm install
    # - run: npm test

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Run Backend Tests
      run: |
        cd backend
        npm test
