name: Node.js CI

on:
  push:
    branches:
      - main  # Replace with your default branch if it's different
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Specify the Node.js version

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test  # Adjust this if your test script is different

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: [18.x, 20.x, 22.x]

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test 
